//Exercice 1
'use strict'

//1
function minimum(a,b)
{
    if (a < b)
        return a;
    return b;
}

//2
function carre(a)
{
    if (typeof a === "number")
        return a*a;
    else
        return NaN;
}

//3
/**
 *
 * @type {{a: number, b: number}}
 */
let o = {a:3, b:2};
let q = {c:7,d:3};
function aireDuRectangle(Object)
{
    if (typeof Object.a !== Infinity && typeof Object.b !== Infinity && Object.a > 0 && Object.b > 0)
        return Object.a * Object.b;
    return -1;
}
//Note: L'objet doit avoir des attributs de même nom que ceux cités dans la fonction (logique)

//4
function power(x, n = 1)
{
    let res;

    if (n >= 0)
    {
        res = x;
        for (let i = 1 ; i < n ; i ++)
            res *= x;
    }
    else res = "Le second argument doit être positif";

    return res;
}

//5
/*function power2(x, n = 1)
{
    let res = x;
    if (n >= 0)
    {
        res *= power2(x, n-1);
        return res;
    }
}*/

function power2(x, n = 1)
{
    if (n > 0)
        return x * power2(x, n-1);
    else
        return 1;
}

/*Autogenerated
function powerRecursion(x, n = 1)
{
    if (n === 1)
        return 1;
    else
        return x * powerRecursion(x, n-1);
}
*/

//typeof NaN renvoie number

//6
function showNumbers(l = 100)
{
    for (let i = 1 ; i <= l ; i ++)
    {
        let msg = i.toString();
        if (i % 3 === 0)
            msg += " woueee";
        if (i % 5 === 0)
            msg += " yoooo";
        if (i % 73 === 0)
            msg += " Biinnngooo!"
        console.log(msg);
    }
}